var descontInfantil = 52.16;
var recreInfantilMatut = 69.28;
var recreInfantilVesp = 65.35;
var descontFund1s1ro = 68.43;
var descontFund1s1 = 63.92;
var descontFund1s2 = 63.25;
var descontFund1s345 = 60.28;
var descontFund2 = 64.23;
var descontMedioMat = 67.66;
var descontTecn75 = 50.00;
var descontTecn77 = 77.80;
var descontTecn72 = 20.00;
var descontTecn76 = 37.00;
var descontTecn78 = 90.769;
var ApostilaInfantil="Apostilas : R$ 450,00 Esse valor pode ser dividido em até 5x de R$ 90,00 no Cartão de Crédito. | Antecipação da Anuidade: R$282,00 Pode ser dividido em até 4x de R$70,50 no Cartão de Crédito."
var ApostilaFund1="Apostilas: R$ 900,00 Esse valor pode ser dividido em até 5x de R$ 180,00 no Cartão de Crédito. | Antecipação da Anuidade: R$282,00 Pode ser dividido em até 4x de R$70,50 no Cartão de Crédito."
var ApostilaFund2="Apostilas: R$ 990,00 Esse valor pode ser dividido em até 5x de R$ 198,00 no Cartão de Crédito. | Antecipação da Anuidade: R$282,00 Pode ser dividido em até 4x de R$70,50 no Cartão de Crédito."
var ApostilaMed1e2="Apostilas: R$ 950,00 Esse valor pode ser dividido em até 5x de R$ 190,00 no Cartão de Crédito. | Antecipação da Anuidade: R$282,00 Pode ser dividido em até 4x de R$70,50 no Cartão de Crédito."
var ApostilaMed3="Apostilas Kapa: R$ 700,00 Esse valor pode ser dividido em até 5x de R$ 140,00 no Cartão de Crédito. | Antecipação da Anuidade: R$282,00 Pode ser dividido em até 4x de R$70,50 no Cartão de Crédito."
var ApostilaMed4="Apostilas: R$157,30"


var cursos = [/*{
					
	cod: 0955,
    curso:"Recreação Infantil Matutino",
    categoria: 1,
    valorIntegral: 814.00,
    docAluno:"Aluno: |- RG |- CPF|- Certidão de Nascimento |- 01 Foto 3x4 |- Comprovante de residência |- Carteirinha de vacinação",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Obrigatório a compra do uniforme escolar no ato da matrícula",
    valorApostila: "",
    idadeMatricula: "Idade para Matrícula:|Recreação Infantil II - 3 anos, até 31 de março do ano letivo.|Recreação Infantil III - 4 anos, até 31 de março do ano letivo.|Recreação Infantil IV - 5 anos, até 31 de março do ano letivo.",
    SegundaMensalidade: "Até o dia 1º R$407,00 | Até o dia 7º R$427,35 | Até o dia 25º R$508,75",
    horaAula: "",
    desconto: recreInfantilMatut,

    vtgEixo:"Recreação Infantil",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Tarde: 12 h 00 min às 17 h 30 min",
    vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia:",
        vtg01: "1 - A Recreação Infantil contribui para integrar a criança ao meio social, desenvolver habilidades motoras, e estimular a curiosidade, autonomia, entre outras coisas;",
        vtg02: "2 - A aprendizagem é realizada através da ludicidade e do desenvolvimento de habilidades e competências;",
        vtg03: "3 - O processo lúdico é realizado por profissionais capacitados e conta com o apoio de auxiliares, obrigatoriamente estudantes de Pedagogia;",
        vtg04: "4 - A estrutura física é adaptada para o desenvolvimento das atividades recreativas do educando com materiais próprios para o desenvolvimento da psicomotricidade (coordenação motora grossa e fina);",
        vtg05: "5 - Atividades como: hora da música, do conto, da arte, da culinária, do montar  e do  relaxar contribuem significativamente para a socialização das crianças;",
        vtg06: "6 - Os banheiros são exclusivos para a utilização dos alunos desse ciclo, que são sempre acompanhados por um responsável;",
        vtg07: "7 - Horário de lanche separado dos demais ciclos com a participação dos professores e auxiliares, aproveitando desse momento para desenvolver habilidades como limpeza, organização e convivência social;",
        vtg08: "8 - A visão de valores familiares proporciona um ambiente sadio além do aprendizado;",
        vtg09: "9 - A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber sobre o desenvolvimento (psicomotor, social e outros) do aluno com hora marcada previamente;",
        vtg10: "10 - O uso do uniforme é obrigatório para que não se tenha comparações entre as crianças.",
},*/{
					
	cod: 0986,
    curso:"Recreação Infantil Vespertino",
    categoria: 1,
    valorIntegral: 814.00,
    docAluno:"Aluno: |- RG |- CPF|- Certidão de Nascimento |- 01 Foto 3x4 |- Comprovante de residência |- Carteirinha de vacinação",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Obrigatório a compra do uniforme escolar no ato da matrícula",
    valorApostila: "",
    idadeMatricula: "Idade para Matrícula:|Recreação Infantil II - 3 anos, até 31 de março do ano letivo.|Recreação Infantil III - 4 anos, até 31 de março do ano letivo.|Recreação Infantil IV - 5 anos, até 31 de março do ano letivo.",
    SegundaMensalidade: "Até o dia 1º R$407,00 | Até o dia 7º R$427,35 | Até o dia 25º R$508,75",
    horaAula: "",
    desconto: recreInfantilVesp,

    vtgEixo:"Recreação Infantil",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Tarde: 12 h 00 min às 17 h 30 min",
    vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia:",
        vtg01: "1 - A Recreação Infantil contribui para integrar a criança ao meio social, desenvolver habilidades motoras, e estimular a curiosidade, autonomia, entre outras coisas;",
        vtg02: "2 - A aprendizagem é realizada através da ludicidade e do desenvolvimento de habilidades e competências;",
        vtg03: "3 - O processo lúdico é realizado por profissionais capacitados e conta com o apoio de auxiliares, obrigatoriamente estudantes de Pedagogia;",
        vtg04: "4 - A estrutura física é adaptada para o desenvolvimento das atividades recreativas do educando com materiais próprios para o desenvolvimento da psicomotricidade (coordenação motora grossa e fina);",
        vtg05: "5 - Atividades como: hora da música, do conto, da arte, da culinária, do montar  e do  relaxar contribuem significativamente para a socialização das crianças;",
        vtg06: "6 - Os banheiros são exclusivos para a utilização dos alunos desse ciclo, que são sempre acompanhados por um responsável;",
        vtg07: "7 - Horário de lanche separado dos demais ciclos com a participação dos professores e auxiliares, aproveitando desse momento para desenvolver habilidades como limpeza, organização e convivência social;",
        vtg08: "8 - A visão de valores familiares proporciona um ambiente sadio além do aprendizado;",
        vtg09: "9 - A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber sobre o desenvolvimento (psicomotor, social e outros) do aluno com hora marcada previamente;",
        vtg10: "10 - O uso do uniforme é obrigatório para que não se tenha comparações entre as crianças.",
},
    
  
{
	cod: 4,	
	curso:"1° Ano do Ensino Fundamental I",
	categoria: 2,
	valorIntegral: 1108.80,
	horario: "12h40 - 16h40",
	docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento |- 01 Foto 3x4 |- Comprovante de residência |- Carteirinha de vacinação |- Declaração de Transferência",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila: ApostilaFund1,
	idadeMatricula: "Idade para Matrícula: |1º Ano - 6 anos até 31 de março do ano letivo.",
	SegundaMensalidade: "Até o dia 1º R$554,40 | Até o dia 7º R$582,12 | Até o dia 25º R$693,00",
	horaAula: "",
	desconto: [descontFund1s1],

	vtgEixo:"ENSINO FUNDAMENTAL I ",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Tarde: 12H e 40min às 17h e 30min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
		vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos cinco anos do curso;",
		vtg02: "2 — Disciplinas além do currículo normal a saber:|- 1° ano: Formação Socioemocional, Inglês, Música e Laboratório de Informática;|- 2° e  3° anos: Formação Socioemocional, Inglês, Música, Laboratório de Informática e Meio Ambiental;|- 4° e 5° anos: Formação Socioemocional, Inglês, Introdução ao Turismo e Laboratório de Informática; | Para ministrar essas disciplinas o aluno passa mais tempo na escola, portanto a carga horária é maior que nas outras escolas;",
        vtg03: "3 - Salas amplas próprias ao ambiente escolar, corredores monitorados pelos inspetores e horário de lanche escalonado sempre monitorado pela professora;",
        vtg04: "4 — Todos os professores de 1º ao 5º ano trabalham com auxiliares do curso de Pedagogia que dão suporte no aprendizado e na disciplina dos alunos;",
        vtg05: "5 – O LÍDER EM MIM: Programa de alto desempenho socioemocional, baseados em hábitos e valores. Com intuito de desenvolver nos alunos habilidades e competências diferenciadas como: responsabilidade, organização, priorização, proatividade, comunicação e etc. Somadas ao processo de ensino – aprendizagem;",
        vtg06: "6 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg07: "7 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg08: "8 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg09: "9 — O uso do uniforme é obrigatório para que não se tenha comparações entre  os alunos, evitando inclusive o bullying;",
        vtg10: "10 — As aulas de Educação Física, são realizadas dentro do próprio período de aula.",
 

},
{
    cod: 789,	
    curso:"1° Ano do Ensino Fundamental I Casa",
    categoria: 2,
    valorIntegral: 1108.80,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento |- 01 Foto 3x4 |- Comprovante de residência |- Carteirinha de vacinação |- Declaração de Transferência",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
    valorApostila: ApostilaFund1,
    idadeMatricula: "Idade para Matrícula: |1º Ano - 6 anos até 31 de março do ano letivo.",
    SegundaMensalidade: "Até o dia 1º R$554,40 | Até o dia 7º R$582,12 | Até o dia 25º R$693,00",
    horaAula: "",
    desconto: descontFund1s1ro,

    vtgEixo:"ENSINO FUNDAMENTAL I ",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Manhã: 07h às 11h 50min. | Tarde: 12H e 40min às 17h e 30min.",
    vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
       vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos cinco anos do curso;",
        vtg02: "2 — Disciplinas além do currículo normal a saber:|- 1° ano: Formação Socioemocional, Inglês, Música e Laboratório de Informática;|- 2° e  3° anos: Formação Socioemocional, Inglês, Música, Laboratório de Informática e Meio Ambiental;|- 4° e 5° anos: Formação Socioemocional, Inglês, Introdução ao Turismo e Laboratório de Informática; | Para ministrar essas disciplinas o aluno passa mais tempo na escola, portanto a carga horária é maior que nas outras escolas;",
        vtg03: "3 - Salas amplas próprias ao ambiente escolar, corredores monitorados pelos inspetores e horário de lanche escalonado sempre monitorado pela professora;",
        vtg04: "4 — Todos os professores de 1º ao 5º ano trabalham com auxiliares do curso de Pedagogia que dão suporte no aprendizado e na disciplina dos alunos;",
        vtg05: "5 – O LÍDER EM MIM: Programa de alto desempenho socioemocional, baseados em hábitos e valores. Com intuito de desenvolver nos alunos habilidades e competências diferenciadas como: responsabilidade, organização, priorização, proatividade, comunicação e etc. Somadas ao processo de ensino – aprendizagem;",
        vtg06: "6 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg07: "7 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg08: "8 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg09: "9 — O uso do uniforme é obrigatório para que não se tenha comparações entre  os alunos, evitando inclusive o bullying;",
        vtg10: "10 — As aulas de Educação Física, são realizadas dentro do próprio período de aula.",
 

},
{
	cod: 5,	
	curso:"2° Ano do Ensino Fundamental I",
	categoria: 2,
	valorIntegral: 1108.80,
	docAluno:"Aluno: |- RG |- CPF|- Certidão de Nascimento |- Comprovante de residência |- 01 Foto 3x4 |- Declaração de Transferência |- Histórico de Transferência |- Carteirinha de Vacinação ;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila: ApostilaFund1,
	idadeMatricula: "",
	SegundaMensalidade: "Até o dia 1º R$554,40 | Até o dia 7º R$582,12 | Até o dia 25º R$693,00",
	horaAula: "",
	desconto: [descontFund1s2],

	vtgEixo:"ENSINO FUNDAMENTAL I ",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Tarde: 12H e 40min às 17h e 30min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
		 vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos cinco anos do curso;",
		 vtg02: "2 — Disciplinas além do currículo normal a saber:|- 1° ano: Formação Socioemocional, Inglês, Música e Laboratório de Informática;|- 2° e  3° anos: Formação Socioemocional, Inglês, Música, Laboratório de Informática e Meio Ambiental;|- 4° e 5° anos: Formação Socioemocional, Inglês, Introdução ao Turismo e Laboratório de Informática; | Para ministrar essas disciplinas o aluno passa mais tempo na escola, portanto a carga horária é maior que nas outras escolas;",
        vtg03: "3 - Salas amplas próprias ao ambiente escolar, corredores monitorados pelos inspetores e horário de lanche escalonado sempre monitorado pela professora;",
        vtg04: "4 — Todos os professores de 1º ao 5º ano trabalham com auxiliares do curso de Pedagogia que dão suporte no aprendizado e na disciplina dos alunos;",
        vtg05: "5 – O LÍDER EM MIM: Programa de alto desempenho socioemocional, baseados em hábitos e valores. Com intuito de desenvolver nos alunos habilidades e competências diferenciadas como: responsabilidade, organização, priorização, proatividade, comunicação e etc. Somadas ao processo de ensino – aprendizagem;",
        vtg06: "6 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg07: "7 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg08: "8 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg09: "9 — O uso do uniforme é obrigatório para que não se tenha comparações entre  os alunos, evitando inclusive o bullying;",
        vtg10: "10 — As aulas de Educação Física, são realizadas dentro do próprio período de aula.",

},
{
	cod: 6,	
	curso:"3° Ano do Ensino Fundamental I",
	categoria: 2,
	valorIntegral: 1108.80,
	docAluno:"Aluno: |- RG |- CPF|- Certidão de Nascimento |- Comprovante de residência |- 01 Foto 3x4 |- Declaração de Transferência |- Histórico de Transferência |- Carteirinha de Vacinação |- Declaração de Escolaridade;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila: ApostilaFund1,
	idadeMatricula: "",
	SegundaMensalidade: "Até o dia 1º R$554,40 | Até o dia 7º R$582,12 | Até o dia 25º R$693,00",
	horaAula: "",
	desconto: [descontFund1s345],

	vtgEixo:"ENSINO FUNDAMENTAL I ",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Tarde: 12H e 40min às 17h e 30min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
		vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos cinco anos do curso;",
		vtg02: "2 — Disciplinas além do currículo normal a saber:|- 1° ano: Formação Socioemocional, Inglês, Música e Laboratório de Informática;|- 2° e  3° anos: Formação Socioemocional, Inglês, Música, Laboratório de Informática e Meio Ambiental;|- 4° e 5° anos: Formação Socioemocional, Inglês, Introdução ao Turismo e Laboratório de Informática; | Para ministrar essas disciplinas o aluno passa mais tempo na escola, portanto a carga horária é maior que nas outras escolas;",
        vtg03: "3 - Salas amplas próprias ao ambiente escolar, corredores monitorados pelos inspetores e horário de lanche escalonado sempre monitorado pela professora;",
        vtg04: "4 — Todos os professores de 1º ao 5º ano trabalham com auxiliares do curso de Pedagogia que dão suporte no aprendizado e na disciplina dos alunos;",
        vtg05: "5 – O LÍDER EM MIM: Programa de alto desempenho socioemocional, baseados em hábitos e valores. Com intuito de desenvolver nos alunos habilidades e competências diferenciadas como: responsabilidade, organização, priorização, proatividade, comunicação e etc. Somadas ao processo de ensino – aprendizagem;",
        vtg06: "6 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg07: "7 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg08: "8 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg09: "9 — O uso do uniforme é obrigatório para que não se tenha comparações entre  os alunos, evitando inclusive o bullying;",
        vtg10: "10 — As aulas de Educação Física, são realizadas dentro do próprio período de aula.",

},
{
	cod: 7,	
	curso:"4° Ano do Ensino Fundamental I",
	categoria: 2,
	valorIntegral: 1108.80,
	docAluno:"Aluno: |- RG |- CPF|- Certidão de Nascimento |- Comprovante de residência |- 01 Foto 3x4 |- Declaração de Transferência |- Histórico de Transferência |- Carteirinha de Vacinação |- Declaração de Escolaridade;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila: ApostilaFund1,
	idadeMatricula: "",
	SegundaMensalidade: "Até o dia 1º R$554,40 | Até o dia 7º R$582,12 | Até o dia 25º R$693,00",
	horaAula: "",
	desconto: [descontFund1s345],

	vtgEixo:"ENSINO FUNDAMENTAL I ",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Tarde: 12H e 40min às 17h e 30min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
		vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos cinco anos do curso;",
		vtg02: "2 — Disciplinas além do currículo normal a saber:|- 1° ano: Formação Socioemocional, Inglês, Música e Laboratório de Informática;|- 2° e  3° anos: Formação Socioemocional, Inglês, Música, Laboratório de Informática e Meio Ambiental;|- 4° e 5° anos: Formação Socioemocional, Inglês, Introdução ao Turismo e Laboratório de Informática; | Para ministrar essas disciplinas o aluno passa mais tempo na escola, portanto a carga horária é maior que nas outras escolas;",
        vtg03: "3 - Salas amplas próprias ao ambiente escolar, corredores monitorados pelos inspetores e horário de lanche escalonado sempre monitorado pela professora;",
        vtg04: "4 — Todos os professores de 1º ao 5º ano trabalham com auxiliares do curso de Pedagogia que dão suporte no aprendizado e na disciplina dos alunos;",
        vtg05: "5 – O LÍDER EM MIM: Programa de alto desempenho socioemocional, baseados em hábitos e valores. Com intuito de desenvolver nos alunos habilidades e competências diferenciadas como: responsabilidade, organização, priorização, proatividade, comunicação e etc. Somadas ao processo de ensino – aprendizagem;",
        vtg06: "6 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg07: "7 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg08: "8 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg09: "9 — O uso do uniforme é obrigatório para que não se tenha comparações entre  os alunos, evitando inclusive o bullying;",
        vtg10: "10 — As aulas de Educação Física, são realizadas dentro do próprio período de aula.",
},
{
	cod: 8,	
	curso:"5° Ano do Ensino Fundamental I",
	categoria: 2,
	valorIntegral: 1108.80,
	docAluno:"Aluno: |- RG |- CPF|- Certidão de Nascimento |- Comprovante de residência |- 01 Foto 3x4 |- Declaração de Transferência |- Histórico de Transferência |- Carteirinha de Vacinação |- Declaração de Escolaridade;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila: ApostilaFund1,
	idadeMatricula: "",
	SegundaMensalidade: "Até o dia 1º R$554,40 | Até o dia 7º R$582,12 | Até o dia 25º R$693,00",
	horaAula: "",
	desconto: [descontFund1s345],

	vtgEixo:"ENSINO FUNDAMENTAL I ",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Tarde: 12H e 40min às 17h e 30min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
		vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos cinco anos do curso;",
		vtg02: "2 — Disciplinas além do currículo normal a saber:|- 1° ano: Formação Socioemocional, Inglês, Música e Laboratório de Informática;|- 2° e  3° anos: Formação Socioemocional, Inglês, Música, Laboratório de Informática e Meio Ambiental;|- 4° e 5° anos: Formação Socioemocional, Inglês, Introdução ao Turismo e Laboratório de Informática; | Para ministrar essas disciplinas o aluno passa mais tempo na escola, portanto a carga horária é maior que nas outras escolas;",
        vtg03: "3 - Salas amplas próprias ao ambiente escolar, corredores monitorados pelos inspetores e horário de lanche escalonado sempre monitorado pela professora;",
        vtg04: "4 — Todos os professores de 1º ao 5º ano trabalham com auxiliares do curso de Pedagogia que dão suporte no aprendizado e na disciplina dos alunos;",
        vtg05: "5 – O LÍDER EM MIM: Programa de alto desempenho socioemocional, baseados em hábitos e valores. Com intuito de desenvolver nos alunos habilidades e competências diferenciadas como: responsabilidade, organização, priorização, proatividade, comunicação e etc. Somadas ao processo de ensino – aprendizagem;",
        vtg06: "6 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg07: "7 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg08: "8 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg09: "9 — O uso do uniforme é obrigatório para que não se tenha comparações entre  os alunos, evitando inclusive o bullying;",
        vtg10: "10 — As aulas de Educação Física, são realizadas dentro do próprio período de aula.",
},
{
	cod: 9,	
	curso:"6° Ano do Ensino Fundamental II",
	categoria: 3,
	valorIntegral: 1377.20,
	docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento |- Comprovante de residência |- 01 Foto 3X4 |- Declaração de Transferência |- Histórico de Transferência |- Carteirinha de Vacinação |- Declaração de Escolaridade;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila: ApostilaFund2,
	idadeMatricula: "",
	SegundaMensalidade: "Até o dia 1º R$688,60 | Até o dia 7º R$723,03 | Até o dia 25º R$860,75",
	horaAula: "",
	desconto: [descontFund2],

	vtgEixo:"ENSINO FUNDAMENTAL II",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Manhã: 07h às 12h 20min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
		vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos quatro anos do curso;",
        vtg02: "2 — Disciplinas além do currículo normal a saber: Desenho Geométrico, Inglês, Espanhol, Laboratórios de Física, Química, Biologia e Informática. Ao ter contato com essas disciplinas desde cedo, conhecendo equipamentos e realizando experiências que fazem toda diferença no despertar da vida acadêmica das disciplinas futuras, nossos alunos terão uma carga horária maior que nas outras escolas;",
        vtg03: "3 — Salas amplas próprias ao ambiente escolar, horário de lanche escalonado e corredores sempre monitorados pelos inspetores.",
        vtg04: "4 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg05: "5 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg06: "6 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg07: "7 — Os pais ou responsáveis podem visualizar ON-LINE ocorrências, boletim e até mesmo o financeiro através do terminal WEB, assim como acompanhar a vida escolar do aluno ou importantes acontecimentos dentro da escola;",
        vtg08: "8 — Plurall: Inovação tecnológica para realização de tarefas por aplicativo de celular ou pela Web. Além das tarefas, disponibiliza plantão de dúvidas, com monitores virtuais, para responder toda e qualquer dúvida dos alunos formando um grande banco de dados para consulta;",
        vtg09: "9 — O uso do uniforme é obrigatório para que não se tenha comparações entre os alunos, evitando inclusive o bullying;",
        vtg10: "10 — As aulas de Educação Física, são realizadas em períodos contrário a matrícula realizada.",

},
{
	cod:10,
	curso:"7° Ano do Ensino Fundamental II",
	categoria: 3,
	valorIntegral: 1377.20,
	docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento |- Comprovante de residência |- 01 Foto 3X4 |- Declaração de Transferência |- Histórico de Transferência |- Carteirinha de Vacinação |- Declaração de Escolaridade;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila: ApostilaFund2,
	idadeMatricula: "",					
	SegundaMensalidade: "Até o dia 1º R$688,60 | Até o dia 7º R$723,03 | Até o dia 25º R$860,75",
	horaAula: "",
	desconto: [descontFund2],

	vtgEixo:"ENSINO FUNDAMENTAL II",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Manhã: 07h às 12h 20min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
        vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos quatro anos do curso;",
        vtg02: "2 — Disciplinas além do currículo normal a saber: Desenho Geométrico, Inglês, Espanhol, Laboratórios de Física, Química, Biologia e Informática. Ao ter contato com essas disciplinas desde cedo, conhecendo equipamentos e realizando experiências que fazem toda diferença no despertar da vida acadêmica das disciplinas futuras, nossos alunos terão uma carga horária maior que nas outras escolas;",
        vtg03: "3 — Salas amplas próprias ao ambiente escolar, horário de lanche escalonado e corredores sempre monitorados pelos inspetores.",
        vtg04: "4 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg05: "5 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg06: "6 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg07: "7 — Os pais ou responsáveis podem visualizar ON-LINE ocorrências, boletim e até mesmo o financeiro através do terminal WEB, assim como acompanhar a vida escolar do aluno ou importantes acontecimentos dentro da escola;",
        vtg08: "8 — Plurall: Inovação tecnológica para realização de tarefas por aplicativo de celular ou pela Web. Além das tarefas, disponibiliza plantão de dúvidas, com monitores virtuais, para responder toda e qualquer dúvida dos alunos formando um grande banco de dados para consulta;",
        vtg09: "9 — O uso do uniforme é obrigatório para que não se tenha comparações entre os alunos, evitando inclusive o bullying;",
        vtg10: "10 — As aulas de Educação Física, são realizadas em períodos contrário a matrícula realizada.",

},
{
	cod: 11,	
	curso:"8° Ano do Ensino Fundamental II",
	categoria: 3,
	valorIntegral: 1377.20,
	docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento |- Comprovante de residência |- 01 Foto 3X4 |- Declaração de Transferência |- Histórico de Transferência |- Carteirinha de Vacinação |- Declaração de Escolaridade;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula.",
	valorApostila: ApostilaFund2,
	idadeMatricula: "",	
	SegundaMensalidade: "Até o dia 1º R$688,60 | Até o dia 7º R$723,03 | Até o dia 25º R$860,75",
	horaAula: "",
	desconto: [descontFund2],

	vtgEixo:"ENSINO FUNDAMENTAL II",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Manhã: 07h às 12h 20min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
	vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos quatro anos do curso;",
        vtg02: "2 — Disciplinas além do currículo normal a saber: Desenho Geométrico, Inglês, Espanhol, Laboratórios de Física, Química, Biologia e Informática. Ao ter contato com essas disciplinas desde cedo, conhecendo equipamentos e realizando experiências que fazem toda diferença no despertar da vida acadêmica das disciplinas futuras, nossos alunos terão uma carga horária maior que nas outras escolas;",
        vtg03: "3 — Salas amplas próprias ao ambiente escolar, horário de lanche escalonado e corredores sempre monitorados pelos inspetores.",
        vtg04: "4 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg05: "5 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg06: "6 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg07: "7 — Os pais ou responsáveis podem visualizar ON-LINE ocorrências, boletim e até mesmo o financeiro através do terminal WEB, assim como acompanhar a vida escolar do aluno ou importantes acontecimentos dentro da escola;",
        vtg08: "8 — Plurall: Inovação tecnológica para realização de tarefas por aplicativo de celular ou pela Web. Além das tarefas, disponibiliza plantão de dúvidas, com monitores virtuais, para responder toda e qualquer dúvida dos alunos formando um grande banco de dados para consulta;",
        vtg09: "9 — O uso do uniforme é obrigatório para que não se tenha comparações entre os alunos, evitando inclusive o bullying;",
        vtg10: "10 — As aulas de Educação Física, são realizadas em períodos contrário a matrícula realizada.",
},
{
	cod: 12,	
	curso:"9° Ano do Ensino Fundamental II",
	categoria: 3,
	valorIntegral: 1377.20,
	docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento |- Comprovante de residência |- 01 Foto 3X4 |- Declaração de Transferência |- Histórico de Transferência |- Carteirinha de Vacinação |- Declaração de Escolaridade;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila: ApostilaFund2,
	idadeMatricula: "",	
	SegundaMensalidade: "Até o dia 1º R$688,60 | Até o dia 7º R$723,03 | Até o dia 25º R$860,75",
	horaAula: "",
	desconto: [descontFund2],

	vtgEixo:"ENSINO FUNDAMENTAL II",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Manhã: 07h às 12h 20min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
		vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos quatro anos do curso;",
        vtg02: "2 — Disciplinas além do currículo normal a saber: Desenho Geométrico, Inglês, Espanhol, Laboratórios de Física, Química, Biologia e Informática. Ao ter contato com essas disciplinas desde cedo, conhecendo equipamentos e realizando experiências que fazem toda diferença no despertar da vida acadêmica das disciplinas futuras, nossos alunos terão uma carga horária maior que nas outras escolas;",
        vtg03: "3 — Salas amplas próprias ao ambiente escolar, horário de lanche escalonado e corredores sempre monitorados pelos inspetores.",
        vtg04: "4 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg05: "5 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg06: "6 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg07: "7 — Os pais ou responsáveis podem visualizar ON-LINE ocorrências, boletim e até mesmo o financeiro através do terminal WEB, assim como acompanhar a vida escolar do aluno ou importantes acontecimentos dentro da escola;",
        vtg08: "8 — Plurall: Inovação tecnológica para realização de tarefas por aplicativo de celular ou pela Web. Além das tarefas, disponibiliza plantão de dúvidas, com monitores virtuais, para responder toda e qualquer dúvida dos alunos formando um grande banco de dados para consulta;",
        vtg09: "9 — O uso do uniforme é obrigatório para que não se tenha comparações entre os alunos, evitando inclusive o bullying;",
        vtg10: "10 — As aulas de Educação Física, são realizadas em períodos contrário a matrícula realizada.",

},
{
	cod: 13,	
	curso:"1° Ensino Médio - Matutino",
	categoria: 4,
	valorIntegral: 1620.30,
	docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Comprovante de residência |- 01 Foto 3x4 |- Carteirinha de Vacinação |- Histórico do Ens. Fundamental com GDAE ou Transferência |- Declaração de Transferência |- Histórico de Transferência |Obs: na ausência do histórico com gdae deverá entregar uma declaração de conclusão do ensino fundamental |- Declaração de Escolaridade;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila:  ApostilaMed1e2,
	idadeMatricula: "",	
	SegundaMensalidade: "Até o dia 1º R$810,15 | Até o dia 7º R$850,65 | Até o dia 25º R$1012,68",
	horaAula: "",
	desconto: [descontMedioMat],

	vtgEixo:"ENSINO MÉDIO",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Manhã: 07h às 12h 20min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
	vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos três anos do curso;",
        vtg02: "2 — As disciplinas são divididas por setores o que facilita para a compreensão dos alunos, por exemplo: Língua Portuguesa fica dividido através dos setores: Gramática, Literatura e Redação;",
        vtg03: "3 — Salas amplas próprias ao ambiente escolar, corredores e horário de lanche sempre monitorados pelos inspetores;",
        vtg04: "4 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg05: "5 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg06: "6 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg07: "7 — Os pais ou responsáveis podem visualizar ON-LINE ocorrências, boletim e até mesmo o financeiro através do terminal WEB, acompanhar a vida escolar do aluno ou importantes acontecimentos dentro da escola;",
        vtg08: "8 — Plurall: Inovação tecnológica para realização de tarefas por aplicativo de celular ou pela Web. Além das tarefas, disponibiliza plantão de dúvidas, com monitores virtuais, para responder toda e qualquer dúvida dos alunos formando um grande banco de dados para consulta;",
        vtg09: "9 — Aplicações de SIMULADOS PROVA ENEM (durante o ano letivo);",
        vtg10: "10 — O uso do uniforme é obrigatório para que não se tenha comparações entre os alunos, evitando inclusive o bullying;",
        vtg11: "11 - As aulas de Educação Física, são realizadas em períodos contrário a matrícula realizada."
},
{
	cod: 14,	
	curso:"2° Ensino Médio - Matutino",
	categoria: 4,
	valorIntegral: 1620.30,
	docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Comprovante de residência |- 01 Foto 3x4 |- Carteirinha de Vacinação |- Histórico do Ens. Fundamental com GDAE ou Transferência |- Declaração de Transferência |- Histórico de Transferência |Obs: na ausência do histórico com gdae deverá entregar uma declaração de conclusão do ensino fundamental |- Declaração de Escolaridade;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila: ApostilaMed1e2,
	idadeMatricula: "",	
	SegundaMensalidade: "Até o dia 1º R$810,15 | Até o dia 7º R$850,65 | Até o dia 25º R$1012,68",
	horaAula: "",
	desconto: [descontMedioMat],

	vtgEixo:"ENSINO MÉDIO",
	vtgLetivo:"",
	vtgHorario:"Horário das Aulas | Manhã: 07h às 12h 20min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
		vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos três anos do curso;",
        vtg02: "2 — As disciplinas são divididas por setores o que facilita para a compreensão dos alunos, por exemplo: Língua Portuguesa fica dividido através dos setores: Gramática, Literatura e Redação;",
        vtg03: "3 — Salas amplas próprias ao ambiente escolar, corredores e horário de lanche sempre monitorados pelos inspetores;",
        vtg04: "4 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg05: "5 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg06: "6 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg07: "7 — Os pais ou responsáveis podem visualizar ON-LINE ocorrências, boletim e até mesmo o financeiro através do terminal WEB, acompanhar a vida escolar do aluno ou importantes acontecimentos dentro da escola;",
        vtg08: "8 — Plurall: Inovação tecnológica para realização de tarefas por aplicativo de celular ou pela Web. Além das tarefas, disponibiliza plantão de dúvidas, com monitores virtuais, para responder toda e qualquer dúvida dos alunos formando um grande banco de dados para consulta;",
        vtg09: "9 — Aplicações de SIMULADOS PROVA ENEM (durante o ano letivo);",
        vtg10: "10 — O uso do uniforme é obrigatório para que não se tenha comparações entre os alunos, evitando inclusive o bullying;",
        vtg11: "11 - As aulas de Educação Física, são realizadas em períodos contrário a matrícula realizada."

},
{
	cod: 15,	
	curso:"3° Ensino Médio - Matutino",
	categoria: 4,
	valorIntegral:  1620.30,
	docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Comprovante de residência |- 01 Foto 3x4 |- Carteirinha de Vacinação |- Histórico do Ens. Fundamental com GDAE ou Transferência |- Declaração de Transferência |- Histórico de Transferência |Obs: na ausência do histórico com gdae deverá entregar uma declaração de conclusão do ensino fundamental |- Declaração de Escolaridade;",
	docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência|- Declaração de Adimplência |- Obrigatório a compra do uniforme escolar no ato da matrícula",
	valorApostila:  ApostilaMed3,
	idadeMatricula: "",	
	SegundaMensalidade: "Até o dia 1º R$810,15 | Até o dia 7º R$850,65 | Até o dia 25º R$1012,68",
	horaAula: "",
	desconto: [descontMedioMat],

	vtgEixo:"ENSINO MÉDIO",
	vtgLetivo:"",
	vtgHorario:" Horário das Aulas | Manhã: 07h às 12h 40min.",
	vtgVantagens:"Quais as vantagens de estudar no Colégio Adélia: ",
		vtg01: "1 — Professores capacitados para o aprendizado dos alunos e no desenvolvimento curricular nos três anos do curso;",
        vtg02: "2 — As disciplinas são divididas por setores o que facilita para a compreensão dos alunos, por exemplo: Língua Portuguesa fica dividido através dos setores: Gramática, Literatura e Redação;",
        vtg03: "3 — Salas amplas próprias ao ambiente escolar, corredores e horário de lanche sempre monitorados pelos inspetores;",
        vtg04: "4 — Todo o aprendizado do curso é feito através do SISTEMA ANGLO DE ENSINO com apoio a plataforma PLURALL;",
        vtg05: "5 — Ao decorrer do ano letivo realizamos eventos proporcionando sempre um ambiente tranquilo e familiar;",
        vtg06: "6 — A escola conta com uma equipe pedagógica sempre presente, tendo os pais à possibilidade de saber a vida acadêmica do aluno com hora marcada previamente;",
        vtg07: "7 — Os pais ou responsáveis podem visualizar ON-LINE ocorrências, boletim e até mesmo o financeiro através do terminal WEB, acompanhar a vida escolar do aluno ou importantes acontecimentos dentro da escola;",
        vtg08: "8 — Plurall: Inovação tecnológica para realização de tarefas por aplicativo de celular ou pela Web. Além das tarefas, disponibiliza plantão de dúvidas, com monitores virtuais, para responder toda e qualquer dúvida dos alunos formando um grande banco de dados para consulta;",
        vtg09: "9 — Aplicações de SIMULADOS PROVA ENEM (durante o ano letivo);",
        vtg10: "10 — O uso do uniforme é obrigatório para que não se tenha comparações entre os alunos, evitando inclusive o bullying;",
        vtg11: "11 - As aulas de Educação Física, são realizadas em períodos contrário a matrícula realizada."
},

]