var descontTecn75 = 59.33;
var descontTecn77 = 77.80;
var descontTecn72 = 20.00;
var descontTecn76 = 37.00;
var descontTecn78 = 90.769;
var descontTecn79 = 50.00;
var descontTecn80 = 77.77;
var descontTecn71 = 0.00;
var MaterialTecnico = "- Material didático incluso.";
var Parcela18meses = "- R$99,00 (Noventa e Nove Reais) no ato da matrícula + 21 parcelas mensáis.";
var Parcela12meses = "- R$99,00 (Noventa e Nove Reais) no ato da matrícula + 14 parcelas mensáis.";
var Parcela7meses = "- R$99,00 (Noventa e Nove Reais) no ato da matrícula + 7 parcelas mensáis.";



var cursos = [{
    cod: 22,
    curso:"Administração",
    categoria: 0,
    presencial:5,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "-Taxa de Matricula R$99,00 (Noventa e Nove Reais)|-21 parcelas mensais |",
    idadeMatricula: MaterialTecnico,
    horaAula: "",
    desconto: descontTecn79,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia:",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
},
{
    cod: 23,
    curso:"Eletrônica",
    categoria: 0,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "|- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn76,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
},
{
    cod: 24,
    curso:"Eletrotécnica",
    categoria: 0,
    flex: 11,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "-Taxa de Matricula R$99,00 (Noventa e Nove Reais)|-21 parcelas mensais |",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn76,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
},
{
    cod: 25,
    curso:"Enfermagem",
    categoria: 0,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn72,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",

},
{
    cod: 26,
    curso:"Estética",
    categoria: 0,
    valorIntegral: 1473.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn75,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",

},
{
    cod: 27,
    curso:"Farmácia",
    categoria: 0,
    valorIntegral: 450.00,
    horario: "12h40 - 16h40",
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn76,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",

},
{/*
    cod: 40,
    curso:"Presencial",
    categoria: 20,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn75,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
*/},
{
    cod: 35,
    curso:"Instrumentação Cirúrgica",
    categoria: 15,
    valorIntegral: 1473.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Auxiliar de Enfermagem com GDAE |- Histórico do Técnico de Enfermagem com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- Total de 6 parcelas mensais |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: 59.26,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
},
{
    cod: 29,
    curso:"Logística",
    categoria: 0,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn75,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",

},
{
    cod: 30,
    curso:"Petróleo e Gás",
    categoria: 0,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn71,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",

},
{
    cod: 31,
    curso:"Portos",
    categoria: 0,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    desconto: descontTecn75,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    horaAula: "",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",

},
{
    cod: 32,
    curso:"Radiologia",
    categoria: 0,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn76,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",

},
{
    cod: 33,
    curso:"Segurança do Trabalho",
    categoria: 0,
    flex: 11,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn75,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",

},
{
    cod: 34,
    curso:"Telecomunicações",
    categoria: 0,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn71,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
},
{/*
    cod: 45,
    curso:"Turismo",
    categoria: 0,
    valorIntegral: 1300.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",	
    horaAula: "",
    desconto: descontTecn75,

    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia: ",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",




},
{
    cod: 36,
    curso:"Educação de Jovens e Adultos (EJA) - Ensino Médio",
    categoria: 28,
    valorIntegral: 99.99,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 12 parcelas mensais |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: 0.00,

    vtgEixo:"",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"",
        vtg01: "",
        vtg02: "",
        vtg03: "",
        vtg04: "",
        vtg05: "",
        vtg06: "",
        vtg07: "",
        vtg08: "",
        vtg09: "",
        vtg10: "",
},
{
    cod: 37,
    curso:"Técnico em Eletrotécnica",
    categoria: 7,
    valorIntegral: 1300.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 12 parcelas mensais |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: descontTecn78,

    vtgEixo:"",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"",
        vtg01: "",
        vtg02: "",
        vtg03: "",
        vtg04: "",
        vtg05: "",
        vtg06: "",
        vtg07: "",
        vtg08: "",
        vtg09: "",
        vtg10: "",
},
{
    cod: 38,
    curso:"Técnico em Informática",
    categoria: 7,
    valorIntegral: 1300.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 12 parcelas mensais |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: descontTecn78,

    vtgEixo:"",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"",
        vtg01: "",
        vtg02: "",
        vtg03: "",
        vtg04: "",
        vtg05: "",
        vtg06: "",
        vtg07: "",
        vtg08: "",
        vtg09: "",
        vtg10: "",
},
{
    cod: 39,
    curso:"Técnico em Segurança do Trabalho",
    categoria: 7,
    valorIntegral: 1300.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 12 parcelas mensais |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: descontTecn78,

    vtgEixo:"",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"",
        vtg01: "",
        vtg02: "",
        vtg03: "",
        vtg04: "",
        vtg05: "",
        vtg06: "",
        vtg07: "",
        vtg08: "",
        vtg09: "",
        vtg10: "",
}
,{
    // essa categoria esta alterando o curso de informatica na calculadora
    cod: 41,
    curso:"Técnico em Guia de Turismo",
    categoria: 8,
    valorIntegral: 210.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "-Taxa de Matricula R$99,00 (Noventa e Nove Reais)|-21 parcelas mensais |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: 0.00,

    vtgEixo:"",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"",
        vtg01: "",
        vtg02: "",
        vtg03: "",
        vtg04: "",
        vtg05: "",
        vtg06: "",
        vtg07: "",
        vtg08: "",
        vtg09: "",
        vtg10: "",
*/},
{ 
    cod: 124,
curso:"Presencial",
categoria: 19,
valorIntegral: 450.00,
docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
idadeMatricula: "",
horaAula: "",
desconto: descontTecn76,

 vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Manhã: 07h às 11h 20min. | Noite: 18h e 05min às 22h e 20min.",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia:",
    vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
    vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
    vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
    vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
    vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
    vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
    vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
    vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
    vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
    vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
},
{/*
    cod: 39,
    curso:"Ead",
    categoria: 20,
    valorIntegral: 1300.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 12 parcelas mensais |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto:descontTecn78,

    vtgEixo:"",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"",
        vtg01: "",
        vtg02: "",
        vtg03: "",
        vtg04: "",
        vtg05: "",
        vtg06: "",
        vtg07: "",
        vtg08: "",
        vtg09: "",
        vtg10: "",
},
{
    cod: 41,
    curso:"Flex",
    categoria: 20,
    valorIntegral: 210.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: 0.00,

    vtgEixo:"",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"",
        vtg01: "",
        vtg02: "",
        vtg03: "",
        vtg04: "",
        vtg05: "",
        vtg06: "",
        vtg07: "",
        vtg08: "",
        vtg09: "",
        vtg10: "",
*/},{ cod: 97,
    curso:"Presencial",
    categoria: 20,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: descontTecn75,
    
     vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Manhã: 07h às 11h 20min. | Noite: 18h e 05min às 22h e 20min.",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia:",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
    },
    { 
        cod: 87,
        curso:"Presencial",
        categoria: 22,
        valorIntegral: 450.00,
        docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
        docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
        valorApostila: "- 14 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
        idadeMatricula: "",
        horaAula: "",
        desconto: descontTecn79,
        
        vtgEixo:"EDUCAÇÃO PROFISSIONAL",
        vtgLetivo:"",
        vtgHorario:"Horário das Aulas | Manhã: 07h às 11h 20min. | Noite: 18h e 05min às 22h e 20min.",
        vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia:",
            vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
            vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
            vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
            vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
            vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
            vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
            vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
            vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
            vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
            vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
        },
        /*{
    cod: 302,
    curso:"Flex",
    categoria: 17,
    valorIntegral: 210.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 14 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: 0.00,

    vtgEixo:"",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"",
        vtg01: "",
        vtg02: "",
        vtg03: "",
        vtg04: "",
        vtg05: "",
        vtg06: "",
        vtg07: "",
        vtg08: "",
        vtg09: "",
        vtg10: "",
},{/*
            cod: 39,
            curso:"Ead",
            categoria: 23,
            valorIntegral: 1300.00,
            docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
            docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
            valorApostila: "- 12 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
            idadeMatricula: "",
            horaAula: "",
            desconto: descontTecn78,
        
            vtgEixo:"",
            vtgLetivo: "",
            vtgHorario:"",
            vtgVantagens:"",
                vtg01: "",
                vtg02: "",
                vtg03: "",
                vtg04: "",
                vtg05: "",
                vtg06: "",
                vtg07: "",
                vtg08: "",
                vtg09: "",
                vtg10: "",
        },
        {
            cod: 41,
            curso:"Flex",
            categoria: 23,
            valorIntegral: 210.00,
            docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
            docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
            valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
            idadeMatricula: "",
            horaAula: "",
            desconto: 0.00,
        
            vtgEixo:"",
            vtgLetivo: "",
            vtgHorario:"",
            vtgVantagens:"",
                vtg01: "",
                vtg02: "",
                vtg03: "",
                vtg04: "",
                vtg05: "",
                vtg06: "",
                vtg07: "",
                vtg08: "",
                vtg09: "",
                vtg10: "",
        },{/*
            cod: 28,
            curso:"Ead",
            categoria: 28,
            valorIntegral: 210.00,
            docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
            docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
            valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
            idadeMatricula: "",
            horaAula: "",
            desconto: 0.00,
        
            vtgEixo:"",
            vtgLetivo: "",
            vtgHorario:"",
            vtgVantagens:"",
                vtg01: "",
                vtg02: "",
                vtg03: "",
                vtg04: "",
                vtg05: "",
                vtg06: "",
                vtg07: "",
                vtg08: "",
                vtg09: "",
                vtg10: "",
       },
{
     /*cod: 102,
    curso:"Ead",
    categoria: 99,
    valorIntegral: 1300.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 12 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: descontTecn78,

    vtgEixo:"",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"",
        vtg01: "",
        vtg02: "",
        vtg03: "",
        vtg04: "",
        vtg05: "",
        vtg06: "",
        vtg07: "",
        vtg08: "",
        vtg09: "",
        vtg10: "",
},
{
    cod: 103,
    curso:"Flex",
    categoria: 99,
    valorIntegral: 210.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: 0.00,

    vtgEixo:"",
    vtgLetivo: "",
    vtgHorario:"",
    vtgVantagens:"",
        vtg01: "",
        vtg02: "",
        vtg03: "",
        vtg04: "",
        vtg05: "",
        vtg06: "",
        vtg07: "",
        vtg08: "",
        vtg09: "",
        vtg10: "",
},*/
{ cod: 101,
    curso:"Presencial",
    categoria: 99,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: descontTecn76,
    
    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Manhã: 07h às 11h 20min. | Noite: 18h e 05min às 22h e 20min.",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia:",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
    },
{ 
    cod: 200,
    curso:"Presencial",
    categoria: 14,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: descontTecn72,
    
    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Manhã: 07h às 11h 20min. | Noite: 18h e 05min às 22h e 20min.",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia:",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
    },
    
{ 
    cod: 207,
    curso:"Presencial",
    categoria: 23,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- Material didático incluso.",
    idadeMatricula: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula.",
    horaAula: "",
    desconto: descontTecn75,
    
    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Manhã: 07h às 11h 20min. | Noite: 18h e 05min às 22h e 20min.",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia:",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
    },
    { 
    cod: 205,
    curso:"Presencial",
    categoria: 29,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: descontTecn76,
    
    vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Manhã: 07h às 11h 20min. | Noite: 18h e 05min às 22h e 20min.",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia:",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
    },
    { cod: 206,
    curso:"Presencial",
    categoria: 30,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 21 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: descontTecn79,
    
     vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Manhã: 07h às 11h 20min. | Noite: 18h e 05min às 22h e 20min.",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia:",
        vtg01: "1 — Cursos de duração de 12 a 18 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
    },
    { cod: 209,
    curso:"Presencial",
    categoria: 31,
    valorIntegral: 450.00,
    docAluno:"Aluno: |- RG |- CPF |- Certidão de Nascimento ou Casamento |- Carteirinha de Vacinação |- Comprovante de residência |- 01 Foto 3x4 |- Histórico do Ens. Fundamental com GDAE |- Histórico do Ens. Médio com GDAE",
    docResp: "Responsáveis: |- RG|- CPF|- Comprovante de residência",
    valorApostila: "- 7 parcelas mensáis + R$99,00 (Noventa e Nove Reais) no ato da matrícula |- Material didático incluso.",
    idadeMatricula: "",
    horaAula: "",
    desconto: descontTecn75,
    
    /* vtgEixo:"EDUCAÇÃO PROFISSIONAL",
    vtgLetivo:"",
    vtgHorario:"Horário das Aulas | Manhã: 07h às 11h 20min. | Noite: 18h e 05min às 22h e 20min.",
    vtgVantagens:"Quais as vantagens de estudar na Escola Técnica Adélia:",
        vtg12: "1 — Cursos de duração de 7 meses, com Matriz curricular atualizada, com as necessidades do mercado, e autorizada pelo MEC, com diploma válido em todo o território nacional;",
        vtg02: "2 — Nossos professores são altamente capacitamos para o aprendizado dos alunos, com especializações que fazem toda a diferença no desenvolvimento curricular;",
        vtg03: "3 — O material de estudo é totalmente voltado para a Educação Profissional e para as necessidades do mercado de trabalho, que é apresentado aos alunos em apostilas, dentro de plataformas on-line ou livros;",
        vtg04: "4 — Salas amplas próprias ao ambiente escolar e um sistema de avaliação aprimorado e moderno;",
        vtg05: "5 — Todos os cursos são acompanhados muito de perto por seus coordenadores e diretores, tendo os alunos dia certos na semana e horário para conversarem com eles;",
        vtg06: "6 — O estágio só é obrigatório para a certificação nos cursos de ENFERMAGEM 600 horas e RADIOLOGIA 400 horas. Nesses casos, os estágios são supervisionados por profissionais com graduação na área. A escola tem parcerias com hospitais, clínicas, UPAs, PAM e empresas;",
        vtg07: "7 — Quanto aos estágios não obrigatórios, a escola incentiva e promove parcerias que ajudam os alunos interessados em realizar estágio, que também são atestados e certificados junto com a empresa conveniada.;",
        vtg08: "8 — Os alunos podem visualizar on-line, ocorrências, boletins e até mesmo a ficha financeira através do terminal WEB;",
        vtg09: "9 — Para aumentar as experiências dos alunos, nossa escola promove eventos pedagógicos, debates e visitas técnicas, que levam os alunos para os ambientes de trabalho reais, que enfrentarão depois de formados;",
        vtg10: "10 - Nossos laboratórios são equipados com materiais de última geração, e os alunos são constantemente colocados em situações práticas que facilitam o aprendizado e o projeto pedagógico.",
    },*/}

]